package com.github.hollandjake.com3529;

import java.io.File;
import java.nio.file.InvalidPathException;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import com.github.hollandjake.com3529.generation.Method;
import com.github.hollandjake.com3529.testsuite.TestSuite;

import lombok.experimental.UtilityClass;

@UtilityClass
public class ClassTestGenerator
{
    /**
     * Generate the test for the provided class
     * <p>
     * To save the tests to a location {@link #forClass(String, String)}
     *
     * @param classFilePath The path to the class file being tested
     * @return A list of {@link TestSuite TestSuites}, one for every method in the class file being tested
     */
    public static List<TestSuite> forClass(String classFilePath)
    {
        return forClass(ParseConvert.parse(classFilePath), null);
    }

    /**
     * Generate the tests for the provided class, saving and writing the tests to the output directory provided
     *
     * @param classFilePath   The path to the class file being tested
     * @param outputDirectory The path to the directory where automatic JUnit tests will be generated
     * @return A list of {@link TestSuite TestSuites}, one for every method in the class file being tested
     */
    public static List<TestSuite> forClass(String classFilePath, String outputDirectory)
    {
        return forClass(ParseConvert.parse(classFilePath), new File(outputDirectory));
    }

    /**
     * Generate the tests for the mapped class instance, optionally writing this to the output directory if non-null
     *
     * @param mappedClass     The mapped class generated by the {@link ParseConvert}
     * @param outputDirectory The file representing the directory where the tests should be saved to
     * @return A list of {@link TestSuite TestSuites}, one for every method in the class file being tested
     */
    public static List<TestSuite> forClass(ParseConvert mappedClass, File outputDirectory)
    {
        if (outputDirectory != null && !outputDirectory.exists() && !outputDirectory.mkdirs())
        {
            throw new InvalidPathException("Invalid path provided", outputDirectory.toString());
        }
        Class<?> clazz = mappedClass.getClazz();

        return Arrays.stream(clazz.getMethods())
                     .parallel()
                     .filter(method -> method.getDeclaringClass() == clazz)
                     .map(method -> MethodTestGenerator.forMethod(
                             new Method(mappedClass.getFileUnderTest(),
                                        mappedClass.getPackageName(),
                                        method,
                                        mappedClass.getBranchTree(method)),
                             mappedClass.getPackageName(),
                             outputDirectory
                     ))
                     .collect(Collectors.toList());
    }

    /**
     * This is main entry point to McTest
     *
     * @param args This is an array of arguments for McTest, for example,
     *             -g "Path to class" -o "Path to JUnit output directory".
     */
    public static void main(String[] args)
    {
        if (args.length == 0)
        {
            throw new IllegalArgumentException("No .java file specified");
        }

        String className = null;
        String outputPath = null;
        for (int i = 0; i < args.length - 1; i++)
        {
            if (args[i].equals("-generate") || args[i].equals("-g"))
            {
                className = args[i + 1];
            }
            if (args[i].equals("-output") || args[i].equals("-o"))
            {
                outputPath = args[i + 1];
            }
        }

        // Assume first argument is the classname unless they have specified the command
        if (className == null)
        {
            className = args[0];
        }

        forClass(className, outputPath);
    }
}
